server:
  port: 8050

spring:
  application:
    name: knowledgecontentanalyze
  datasource:
    url: jdbc:mysql://xx.xx.xx.xx/know_share?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: username
    password: password

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.ygcxy.mapper

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
