server:
  port: 10010

# 注册到Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  # 微服务网关配置
  cloud:
    gateway:
      routes:
#        身份验证
        - id: uaa
          uri: http://localhost:8110
          predicates:
            - Path=/api/v1/uaa/**
#        广告管理
        - id: advertise
          uri: http://localhost:8100
          predicates:
            - Path=/api/v1/advertise/**
#        ES业务
        - id: elasticsearch
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/es/**
#        邮件业务
        - id: email
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/email/**
#       知识内容
        - id: knowledgecontent
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/know/**
#       知识评论
        - id: knowledgecomment
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/comments/**
#       知识收藏
        - id: knowledgefavorite
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/collect/**
#       知识点赞
        - id: knowledgelikes
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/likes/**
#       日志
        - id: logs
          uri: http://localhost:8040
          predicates:
            - Path=/api/v1/logs/**
#       注册业务
        - id: register
          uri: http://localhost:8120
          predicates:
            - Path=/api/v1/register/**
#       敏感词模块
        - id: sensitive
          uri: http://localhost:8030
          predicates:
            - Path=/api/v1/sensitive/**
#       用户模块
        - id: user
          uri: http://localhost:8020
          predicates:
            - Path=/api/v1/user/**
#       用户分析模块
        - id: useranalyze
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/analyzeuser/**
#       用户标签分析
        - id: useranalyzecategory
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/category/**
#       文件管理
        - id: file
          uri: http://localhost:8140
          predicates:
            - Path=/api/v1/file/**
#       内容分析
        - id: analyzeknow
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/analyzeknow/**
#       举报管理
        - id: report
          uri: http://localhost:8130
          predicates:
            - Path=/api/v1/report/**
#       用户内容分析模块
        - id: knowuser
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/userknow/**



      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowed-methods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000

